title: The Unix Programming Environment
link: "http://product.half.ebay.com/The-UNIX-Programming-Environment-by-Brian-W-Kernighan-and-Rob-Pike-1983-Other/54385&tg=info"
description: 
section: ğŸ§‘â€ğŸ« Tutorials
tag: tutorials